language: python

install:
    - wget http://repo.continuum.io/archive/Anaconda-1.6.0-Linux-x86_64.sh
    - chmod +x Anaconda-1.6.0-Linux-x86_64.sh
    - bash ./Anaconda-1.6.0-Linux-x86_64.sh -b
    - pip install -r requirements.txt

script: nosetests -w demos/demo1/src
