language: python

install: 
    - pip install Cython==0.22
    - wget http://repo.continuum.io/archive/Anaconda-1.6.0-Linux-x86_64.sh
    - chmod +x Anaconda-1.6.0-Linux-x86_64.sh
    - bash ./Anaconda-1.6.0-Linux-x86_64.sh -b
    - pip install -r requirementsA.txt
    - pip install -r requirements.txt

script: nosetests -s demos/demo1/src
