#! /bin/bash
# chkconfig: 345 99 01
# /etc/init.d/medareda_startup

case "$1" in
  start)
    echo "Starting medareda_startup"
    cd /root/medareda/demos/demo1
    python src/start_server.py > /root/medareda/demos/demo1/log/start_server.log

    echo "Start ipython"
    /root/anaconda/bin/ipython notebook --profile /root/ipython_notebook_config.py
    ;;
  stop)
    echo "Stopping example"
    # kill application you want to stop
    killall python
    ;;
  *)
    echo "Usage: /etc/init.d/medareda_startup{start|stop}"
    exit 1
    ;;
esac

exit 0
